C:\GENIE2k\EXEFILES\PUTVIEW DET:DET01
C:\GENIE2k\EXEFILES\ECAL DET:DET01 /CERT=C:\GENIE2K\CAMFILES\Eu-152.CTF
C:\GENIE2k\EXEFILES\MOVEDATA DET:DET01 c:\tempespe\calib\cnf\calib.CNF /OVERWRITE
C:\GENIE2k\EXEFILES\ENDVIEW