C:\GENIE2k\EXEFILES\PUTVIEW DET:DET01
C:\GENIE2k\EXEFILES\STARTMCA DET:DET01
C:\GENIE2k\EXEFILES\WAIT DET:DET01 /ACQ
C:\GENIE2k\EXEFILES\MOVEDATA DET:DET01 c:\tempespe\cnf\efimero.CNF /OVERWRITE
C:\GENIE2k\EXEFILES\ENDVIEW

